# Site settings
title: Samuel Arnesen
url: ''
baseurl: ''

theme: minima

author: Samuel Arnesen
email: samuel.p.arnesen@gmail.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
future: true
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

github_username: samuelarnesen
linkedin_username: samuel-arnesen
letterboxd_username: sparnesen
goodreads_username: samarnesen

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']